on:
  push:
    branches:
      - master
      - develop
      - rel/*
  pull_request:
    branches:
      - master
      - develop
      - rel/*

name: Rust

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    name: Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --all --all-features

      - name: Cargo check
        run: cargo check --all --all-features

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all --all-targets --all-features

      - name: Test
        run: cargo test --all --all-features

  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Machete
        uses: bnjbvr/cargo-machete@main

  typos:
    # https://github.com/crate-ci/typos
    # install and run locally: cargo install typos-cli && typos
    name: typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling of entire workspace
        uses: crate-ci/typos@master
